# Data Mining and Machine Learning - Project

## Detecting Difficulty Level of French Texts

### Step by step guidelines

The following are a set of step by step guidelines to help you get started with your project for the Data Mining and Machine Learning class. 
To test what you learned in the class, we will hold a competition. You will create a classifier that predicts how the level of some text in French (A1,..., C2). The team with the highest rank will get some goodies in the last class (some souvenirs from tech companies: Amazon, LinkedIn, etc).

**2 people per team**

Choose a team here:
https://moodle.unil.ch/mod/choicegroup/view.php?id=1305831


#### 1. 📂 Create a public GitHub repository for your team using this naming convention `DMML2022_[your_team_name]` with the following structure:
- data (folder) 
- code (folder) 
- documentation (folder)
- a readme file (.md): *mention team name, participants, brief description of the project, approach, summary of results table and link to the explainatory video (see below).*

All team members should contribute to the GitHub repository.

#### 2. 🇰 Join the competititon on Kaggle using the invitation link we sent on Slack.

Under the Team tab, save your team name (`UNIL_your_team_name`) and make sure your team members join in as well. You can merge your user account with your teammates in order to create a team.

#### 3. 📓 Read the data into your colab notebook. There should be one code notebook per team, but all team members can participate and contribute code. 

You can use either direct the Kaggle API and your Kaggle credentials (as explained below and **entirely optional**), or dowload the data form Kaggle and upload it onto your team's GitHub repository under the data subfolder.

#### 4. 💎 Train your models and upload the code under your team's GitHub repo. Set the `random_state=0`.
- baseline
- logistic regression with TFidf vectoriser (simple, no data cleaning)
- KNN & hyperparameter optimisation (simple, no data cleaning)
- Decision Tree classifier & hyperparameter optimisation (simple, no data cleaning)
- Random Forests classifier (simple, no data cleaning)
- another technique or combination of techniques of your choice

BE CREATIVE! You can use whatever method you want, in order to climb the leaderboard. The only rule is that it must be your own work. Given that, you can use all the online resources you want. 

#### 5. 🎥 Create a YouTube video (10-15 minutes) of your solution and embed it in your notebook. Explain the algorithms used and the evaluation of your solutions. *Select* projects will also be presented live by the group during the last class.


### Submission details (one per team)

1. Download a ZIPped file of your team's repository and submit it in Moodle here. IMPORTANT: in the comment of the submission, insert a link to the repository on Github.
https://moodle.unil.ch/mod/assign/view.php?id=1305833



### Grading (one per team)
- 20% Kaggle Rank
- 50% code quality (using classes, splitting into proper files, documentation, etc)
- 15% github quality (include link to video, table with progress over time, organization of code, images, etc)
- 15% video quality (good sound, good slides, interesting presentation).

## Some further details for points 3 and 4 above.

### 3. Read data into your notebook with the Kaggle API (optional but useful). 

You can also download the data from Kaggle and put it in your team's repo the data folder.

In [167]:
# reading in the data via the Kaggle API

# mount your Google Drive
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [168]:
# install Kaggle
! pip install kaggle

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


### IMPORTANT
Log into your Kaggle account, go to Account > API > Create new API token. You will obtain a kaggle.json file. Save it in your Google Drive (not in a folder, in your general drive).

In [169]:
#read in your Kaggle credentials from Google Drive
!cp /content/drive/MyDrive/Coding_Challenge/kaggle.json ~/.kaggle/kaggle.json


In [170]:
# download the dataset from the competition page
! kaggle competitions download -c detecting-french-texts-difficulty-level-2022

detecting-french-texts-difficulty-level-2022.zip: Skipping, found more recently modified local copy (use --force to force download)


In [171]:
#!unzip "detecting-french-texts-difficulty-level-2022.zip" -d data

In [172]:
# read in your training data
import pandas as pd
import numpy as np

df = pd.read_csv('drive/MyDrive/Coding_Challenge/training_data.csv')

In [173]:
df

id                                           sentence difficulty
0        0  Les coûts kilométriques réels peuvent diverger...         C1
1        1  Le bleu, c'est ma couleur préférée mais je n'a...         A1
2        2  Le test de niveau en français est sur le site ...         A1
3        3           Est-ce que ton mari est aussi de Boston?         A1
4        4  Dans les écoles de commerce, dans les couloirs...         B1
...    ...                                                ...        ...
4795  4795  C'est pourquoi, il décida de remplacer les hab...         B2
4796  4796  Il avait une de ces pâleurs splendides qui don...         C1
4797  4797  Et le premier samedi de chaque mois, venez ren...         A2
4798  4798  Les coûts liés à la journalisation n'étant pas...         C2
4799  4799  Sur le sable, la mer haletait de toute la resp...         C2

[4800 rows x 3 columns]

In [174]:
df.difficulty.value_counts()

A1    813
C2    807
C1    798
B1    795
A2    795
B2    792
Name: difficulty, dtype: int64

In [175]:
#Ordinal encode the difficulty
oe = OrdinalEncoder()
oe.set_params(categories = [['A1','A2','B1','B2','C1','C2']])#0 = A1, 1 = A2,...

#fit_transform my column
df['difficulty'] = oe.fit_transform(df[['difficulty']]).astype('int')
df

id                                           sentence  difficulty
0        0  Les coûts kilométriques réels peuvent diverger...           4
1        1  Le bleu, c'est ma couleur préférée mais je n'a...           0
2        2  Le test de niveau en français est sur le site ...           0
3        3           Est-ce que ton mari est aussi de Boston?           0
4        4  Dans les écoles de commerce, dans les couloirs...           2
...    ...                                                ...         ...
4795  4795  C'est pourquoi, il décida de remplacer les hab...           3
4796  4796  Il avait une de ces pâleurs splendides qui don...           4
4797  4797  Et le premier samedi de chaque mois, venez ren...           1
4798  4798  Les coûts liés à la journalisation n'étant pas...           5
4799  4799  Sur le sable, la mer haletait de toute la resp...           5

[4800 rows x 3 columns]

Have a look at the data on which to make predictions.

In [176]:
df_pred = pd.read_csv('drive/MyDrive/Coding_Challenge/unlabelled_test_data.csv')
df_pred.head()

id                                           sentence
0   0  Nous dûmes nous excuser des propos que nous eû...
1   1  Vous ne pouvez pas savoir le plaisir que j'ai ...
2   2  Et, paradoxalement, boire froid n'est pas la b...
3   3  Ce n'est pas étonnant, car c'est une saison my...
4   4  Le corps de Golo lui-même, d'une essence aussi...

And this is the format for your submissions.

In [177]:
df_example_submission = pd.read_csv('drive/MyDrive/Coding_Challenge/sample_submission.csv')
df_example_submission.head()

id difficulty
0   0         A1
1   1         A1
2   2         A1
3   3         A1
4   4         A1

### 4. Train your models

Set your X and y variables. 
Set the `random_state=0`
Split the data into a train and test set using the following parameters `train_test_split(X, y, test_size=0.2, random_state=0)`.

#### 4.1.Baseline
What is the baseline for this classification problem?

In [178]:
np.random.seed = 0

In [179]:
# your code here (you can use as many lines of code as you like)
(df['difficulty'].value_counts() / len(df)).max()

0.169375

#### 4.2. Logistic Regression (without data cleaning)

Train a simple logistic regression model using a Tfidf vectoriser.

In [180]:
# Import required packages

%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
import spacy
from spacy import displacy
sns.set_style("whitegrid")

from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, LabelEncoder
from sklearn.linear_model import LogisticRegression, LogisticRegressionCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn. preprocessing import StandardScaler
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.pipeline import Pipeline


In [181]:
!pip install -U spacy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [182]:
#!python -m spacy download fr_dep_news_trf

In [183]:
!python -m spacy download fr_core_news_sm

2022-11-29 15:54:47.936724: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 16.3 MB 256 kB/s 
✔ Download and installation successful
You can now load the package via spacy.load('fr_core_news_sm')


In [184]:
X = df['sentence']
y = df['difficulty']

In [185]:
# Load French language model
sp = spacy.load('fr_core_news_sm')

In [204]:
def spacy_tokenizer(sentence):
  mytokens = sp(sentence)
  mytokens = [word for word in mytokens]
  return mytokens

In [205]:
spacy_tokenizer(df.iloc[0,1])

[Les,
 coûts,
 kilométriques,
 réels,
 peuvent,
 diverger,
 sensiblement,
 des,
 valeurs,
 moyennes,
 en,
 fonction,
 du,
 moyen,
 de,
 transport,
 utilisé,
 ,,
 du,
 taux,
 d',
 occupation,
 ou,
 du,
 taux,
 de,
 remplissage,
 ,,
 de,
 l',
 infrastructure,
 utilisée,
 ,,
 de,
 la,
 topographie,
 des,
 lignes,
 ,,
 du,
 flux,
 de,
 trafic,
 ,,
 etc.]

In [188]:
df

id                                           sentence  difficulty
0        0  Les coûts kilométriques réels peuvent diverger...           4
1        1  Le bleu, c'est ma couleur préférée mais je n'a...           0
2        2  Le test de niveau en français est sur le site ...           0
3        3           Est-ce que ton mari est aussi de Boston?           0
4        4  Dans les écoles de commerce, dans les couloirs...           2
...    ...                                                ...         ...
4795  4795  C'est pourquoi, il décida de remplacer les hab...           3
4796  4796  Il avait une de ces pâleurs splendides qui don...           4
4797  4797  Et le premier samedi de chaque mois, venez ren...           1
4798  4798  Les coûts liés à la journalisation n'étant pas...           5
4799  4799  Sur le sable, la mer haletait de toute la resp...           5

[4800 rows x 3 columns]

In [206]:
# your code here
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [190]:
#Define a model AND apply vectorizer
LR = LogisticRegression()

In [191]:
# Using default tokenizer in TfidfVectorizer
tfidf = TfidfVectorizer(ngram_range=(1,1), tokenizer = spacy_tokenizer)
# Create a pipeline
pipe = Pipeline([('vectorizer', tfidf),
                 ('classifier', LR)])

# Fit model on training set
pipe.fit(X_train, y_train)

Pipeline(steps=[('vectorizer',
                 TfidfVectorizer(tokenizer=<function spacy_tokenizer at 0x7f8eea4f4f80>)),
                ('classifier', LogisticRegression())])

TfidfVectorizer(tokenizer=<function spacy_tokenizer at 0x7f8eea4f4f80>)


In [192]:
X_train

70                                Comment t'appelles-tu ?
4347    Voilà qui serait en effet de nature à simplifi...
1122    Les pèlerins partagèrent alors cette célébrati...
4570                          Qu'est-ce que vous faites ?
34      En voici un des moins obscurs : "Plus nous dev...
                              ...                        
1033    Les micro-changements apportés par ce type d'u...
3264    J'allais à la poste quand j'ai croisé ma cousi...
1653    Au cours des années 1970 et 1980, plusieurs gr...
2607    Stop : tout d'abord, figurez-vous que les vrai...
2732    "On s'est alors dit que le terrain commençait ...
Name: sentence, Length: 3840, dtype: object

Calculate accuracy, precision, recall and F1 score on the test set.

In [218]:
#function to calculate metrics of the models
def models_metrics (true, pred):
  precision = precision_score(true, pred, average='micro')
  recall = recall_score(true, pred, average='micro')
  f1 = f1_score(true, pred, average='micro')
  print(f"CONFUSION MATRIX:\n{confusion_matrix(true, pred,)}")
  print(f"ACCURACY SCORE:\n{accuracy_score(true, pred):.4f}")
  print(f"CLASSIFICATION REPORT:\n\tPrecision: {precision:.4f}\n\tRecall: {recall:.4f}\n\tF1_Score: {f1:.4f}")

In [216]:
y_pred_lr = pipe.predict(X_test)

In [219]:
models_metrics(y_test,y_pred_lr)

CONFUSION MATRIX:
[[161   0   0   0   0   0]
 [164   0   0   0   0   0]
 [160   0   0   0   0   0]
 [144   0   0   0   0   0]
 [173   0   0   0   0   0]
 [158   0   0   0   0   0]]
ACCURACY SCORE:
0.1677
CLASSIFICATION REPORT:
	Precision: 0.1677
	Recall: 0.1677
	F1_Score: 0.1677


Have a look at the confusion matrix and identify a few examples of sentences that are not well classified.

In [ ]:
# your code here

Generate your first predictions on the `unlabelled_test_data.csv`. make sure your predictions match the format of the `unlabelled_test_data.csv`.

#### 4.3. KNN (without data cleaning)

Train a KNN classification model using a Tfidf vectoriser. Show the accuracy, precision, recall and F1 score on the test set.

In [ ]:
# your code here

Try to improve it by tuning the hyper parameters (`n_neighbors`,   `p`, `weights`).

In [ ]:
# your code here

#### 4.4. Decision Tree Classifier (without data cleaning)

Train a Decison Tree classifier, using a Tfidf vectoriser. Show the accuracy, precision, recall and F1 score on the test set.

In [ ]:
# your code here

Try to improve it by tuning the hyper parameters (`max_depth`, the depth of the decision tree).

In [ ]:
# your code here

#### 4.5. Random Forest Classifier (without data cleaning)

Try a Random Forest Classifier, using a Tfidf vectoriser. Show the accuracy, precision, recall and F1 score on the test set.

In [ ]:
# your code here

#### 4.6. Any other technique, including data cleaning if necessary

Try to improve accuracy by training a better model using the techniques seen in class, or combinations of them.

As usual, show the accuracy, precision, recall and f1 score on the test set.

In [ ]:
# your code here

#### 4.7. Show a summary of your results